fix: rollback runner to fix ARM build issue

diff --git a/.github/workflows/build_nginx.yml b/.github/workflows/build_nginx.yml
--- a/.github/workflows/build_nginx.yml
+++ b/.github/workflows/build_nginx.yml
@@ -7,16 +7,22 @@ on:
 
 jobs:
   build:
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-22.04
+    name: "Build Nginx image"
 
     steps:
       - name: Check out repository
         uses: actions/checkout@v4.2.2
+        with:
+          fetch-depth: 0
+
+      - name: Set up Docker QEMU
+        uses: docker/setup-qemu-action@v3.4.0
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3.8.0
 
-      - name: Login to Docker Hub
+      - name: Login to DockerHub
         uses: docker/login-action@v3.3.0
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
@@ -31,16 +37,14 @@ jobs:
         run: |
           CURRENT_NGINX_VERSION=$(docker run --rm honeok/nginx:alpine nginx -V 2>&1 | grep 'nginx version:' | awk -F'/' '{print $2}')
           if [[ -z $CURRENT_NGINX_VERSION ]]; then
-              echo "ERROR: current nginx version retrieval failed!"
-              exit 1
+              echo "ERROR: current nginx version retrieval failed!" && exit 1
           fi
           echo "CURRENT_NGINX_VERSION=${CURRENT_NGINX_VERSION}" >> $GITHUB_ENV
-          LATEST_NGX_TAG=$(docker run --rm nginx:alpine sh -c 'cat /etc/alpine-release | cut -d "." -f 1-2')
-          if [[ -z $LATEST_NGX_TAG ]]; then
-              echo "ERROR: current nginx tag retrieval failed"
-              exit 1
+          ALPINE_TAG=$(docker run --rm nginx:alpine sh -c 'cat /etc/alpine-release | cut -d "." -f 1-2')
+          if [[ -z $ALPINE_TAG ]]; then
+              echo "ERROR: current nginx tag retrieval failed" && exit 1
           fi
-          echo "LATEST_NGX_TAG=${LATEST_NGX_TAG}" >> $GITHUB_ENV
+          echo "ALPINE_TAG=${ALPINE_TAG}" >> $GITHUB_ENV
 
       - name: Compare nginx version
         run: |
@@ -50,7 +54,7 @@ jobs:
             echo "BUILD_DOCKER_IMAGE=false" >> $GITHUB_ENV
           fi
 
-      - name: Build and Push Docker Image
+      - name: Build and push Nginx image
         if: env.BUILD_DOCKER_IMAGE == 'true'
         uses: docker/build-push-action@v6.11.0
         with:
@@ -58,9 +62,9 @@ jobs:
           file: Dockerfile
           push: true
           tags: |
-            "honeok/nginx:${{ env.LATEST_NGINX_VERSION }}-alpine${{ env.LATEST_NGX_TAG }}"
+            "honeok/nginx:${{ env.LATEST_NGINX_VERSION }}-alpine${{ env.ALPINE_TAG }}"
             "honeok/nginx:alpine"
-          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
+          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/riscv64,linux/s390x
           build-args: |
             NGINX_VERSION=${{ env.LATEST_NGINX_VERSION }}
             ZSTD_VERSION=${{ env.ZSTD_VERSION }}
