refactor: optimize ci pipeline build process

diff --git a/.github/workflows/build_php.yml b/.github/workflows/build_php.yml
--- a/.github/workflows/build_php.yml
+++ b/.github/workflows/build_php.yml
@@ -1,4 +1,4 @@
-name: 'Build and publish php'
+name: 'Build and Publish php'
 
 on:
   schedule:
@@ -7,10 +7,11 @@ on:
 
 jobs:
   build:
-    name: 'Build and publish php'
+    name: 'Build and Publish php'
     runs-on: ubuntu-latest
     env:
       DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
+      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
 
     steps:
       - name: 'Check out repository'
@@ -20,44 +21,46 @@ jobs:
 
       - name: 'Fetch Versions and Determine Build'
         run: |
-          PHP_CVER=$(curl -Lsk "https://hub.docker.com/v2/repositories/honeok/php/tags" | jq -r '.results // [] | .[].name' 2>/dev/null | grep -v '^fpm-alpine$' | sort -Vr | head -n1 | cut -d'-' -f1 || echo "")
-          PHP_LVER=$(curl -Lsk "https://api.github.com/repos/php/php-src/releases/latest" | jq -r '.tag_name | sub("^php-"; "")')
-          PHP_TAG=$(docker run --rm php:fpm-alpine sh -c 'cat /etc/alpine-release | cut -d "." -f 1-2')
-          if [ -z "$PHP_LVER" ] || [ -z "$PHP_TAG" ]; then
-            echo 'Error: Required parameters cannot be empty.' && exit 1
-          fi
-          echo "PHP_CVER=${PHP_CVER}" >> $GITHUB_ENV
-          echo "PHP_LVER=${PHP_LVER}" >> $GITHUB_ENV
-          echo "PHP_TAG=${PHP_TAG}" >> $GITHUB_ENV
-          if [[ "$(echo -e "${{ env.PHP_LVER }}\n${{ env.PHP_CVER }}" | sort -V | head -n1)" != "${{ env.PHP_LVER }}" ]] || [[ -z "$PHP_CVER" ]]; then
-            echo "BUILD_IMAGE=true" >> $GITHUB_ENV
-          else
-            echo "BUILD_IMAGE=false" >> $GITHUB_ENV
+          PHP_CVER=$(curl -fsSL "https://hub.docker.com/v2/repositories/${{ env.DOCKER_USERNAME }}/php/tags" 2>/dev/null | \
+            jq -r ".results // [] | .[].name" | grep -v '^fpm-alpine$' | sort -Vr | head -n1 | cut -d'-' -f1 || echo "") && \
+          PHP_LVER=$(curl -fsSL "https://api.github.com/repos/php/php-src/releases/latest" | \
+            jq -r '.tag_name | sub("^php-"; "")') && \
+          ALPINE_TAG=$(docker run --rm php:fpm-alpine sh -c 'cat /etc/alpine-release | cut -d "." -f 1-2') && \
+          if [ -z "$PHP_LVER" ] || [ -z "$ALPINE_TAG" ]; then \
+            echo 'Error: Required parameters cannot be empty.' && exit 1; \
+          fi && \
+          echo "PHP_CVER=${PHP_CVER}" >> $GITHUB_ENV && \
+          echo "PHP_LVER=${PHP_LVER}" >> $GITHUB_ENV && \
+          echo "ALPINE_TAG=${ALPINE_TAG}" >> $GITHUB_ENV && \
+          if [[ "$(echo -e "${{ env.PHP_LVER }}\n${{ env.PHP_CVER }}" | sort -V | head -n1)" != "${{ env.PHP_LVER }}" ]] || \
+            [[ -z "$PHP_CVER" ]]; then \
+            echo "IS_RENEW=1" >> $GITHUB_ENV; \
           fi
 
       - name: 'Set up Docker QEMU'
-        if: ${{ env.BUILD_IMAGE == true || github.event_name == 'workflow_dispatch' }}
+        if: env.IS_RENEW == 1 || github.event_name == 'workflow_dispatch'
         uses: docker/setup-qemu-action@v3.6.0
 
       - name: 'Set up Docker Buildx'
-        if: ${{ env.BUILD_IMAGE == true || github.event_name == 'workflow_dispatch' }}
+        if: env.IS_RENEW == 1 || github.event_name == 'workflow_dispatch'
         uses: docker/setup-buildx-action@v3.10.0
 
       - name: 'Login to DockerHub'
-        if: ${{ env.BUILD_IMAGE == true || github.event_name == 'workflow_dispatch' }}
+        if: env.IS_RENEW == 1 || github.event_name == 'workflow_dispatch'
         uses: docker/login-action@v3.4.0
         with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
+          username: ${{ env.DOCKER_USERNAME }}
+          password: ${{ env.DOCKER_PASSWORD }}
 
-      - name: 'Build and push PHP image'
-        if: ${{ env.BUILD_IMAGE == true || github.event_name == 'workflow_dispatch' }}
+      - name: 'Build and Push PHP image'
+        if: env.IS_RENEW == 1 || github.event_name == 'workflow_dispatch'
         uses: docker/build-push-action@v6.11.0
         with:
           context: "{{ defaultContext }}:ldnmp/php"
           file: Dockerfile
           push: true
           tags: |
-            "${{ env.DOCKER_USERNAME }}/php:${{ env.PHP_LVER }}-fpm-alpine${{ env.PHP_TAG }}"
+            "${{ env.DOCKER_USERNAME }}/php:${{ env.PHP_LVER }}-fpm-alpine${{ env.ALPINE_TAG }}"
+            "${{ env.DOCKER_USERNAME }}/php:${{ env.PHP_LVER }}-fpm-alpine"
             "${{ env.DOCKER_USERNAME }}/php:fpm-alpine"
           platforms: linux/386, linux/amd64, linux/arm/v7, linux/arm64/v8, linux/ppc64le
