fix: improve and streamline build workflow

diff --git a/.github/workflows/nginxbuild.yml b/.github/workflows/nginxbuild.yml
--- a/.github/workflows/nginxbuild.yml
+++ b/.github/workflows/nginxbuild.yml
@@ -1,9 +1,9 @@
-name: Nginx
+name: Build and publish Nginx
 
 on:
   workflow_dispatch:
   schedule:
-    - cron: '0 16 * * 0' # 东八区每周日的午夜
+    - cron: '0 16 * * 0'
 
 jobs:
   build:
@@ -11,35 +11,38 @@ jobs:
 
     steps:
       - name: Check out repository
-        uses: actions/checkout@v4
+        uses: actions/checkout@v4.2.2
 
       - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
+        uses: docker/setup-buildx-action@v3.8.0
 
       - name: Login to Docker Hub
-        uses: docker/login-action@v3
+        uses: docker/login-action@v3.3.0
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
-      - name: Install dependencies
-        run: sudo apt-get update && sudo apt-get install -y jq curl
-
       - name: Fetch latest versions
         run: |
-          chmod +x ldnmp/nginx/build_depend.sh
-          bash ldnmp/nginx/build_depend.sh
+          chmod +x ldnmp/nginx/build.sh
+          bash ldnmp/nginx/build.sh
 
-      - name: Get Current Version
-        id: get_version
+      - name: Get current version
         run: |
           CURRENT_NGINX_VERSION=$(docker run --rm honeok/nginx:alpine nginx -V 2>&1 | grep 'nginx version:' | awk -F'/' '{print $2}')
-          ALPINE_VERSION=$(docker run --rm nginx:alpine sh -c 'cat /etc/alpine-release | cut -d "." -f 1-2')
+          if [[ -z $CURRENT_NGINX_VERSION ]]; then
+              echo "ERROR: current nginx version retrieval failed!"
+              exit 1
+          fi
           echo "CURRENT_NGINX_VERSION=${CURRENT_NGINX_VERSION}" >> $GITHUB_ENV
-          echo "ALPINE_VERSION=${ALPINE_VERSION}" >> $GITHUB_ENV
+          LATEST_NGX_TAG=$(docker run --rm nginx:alpine sh -c 'cat /etc/alpine-release | cut -d "." -f 1-2')
+          if [[ -z $LATEST_NGX_TAG ]]; then
+              echo "ERROR: current nginx tag retrieval failed"
+              exit 1
+          fi
+          echo "LATEST_NGX_TAG=${LATEST_NGX_TAG}" >> $GITHUB_ENV
 
-      - name: Compare NGINX Version
-        id: compare_nginx_versions
+      - name: Compare nginx version
         run: |
           if [[ "$(echo -e "${{ env.LATEST_NGINX_VERSION }}\n${{ env.CURRENT_NGINX_VERSION }}" | sort -V | head -n1)" != "${{ env.LATEST_NGINX_VERSION }}" ]]; then
             echo "BUILD_DOCKER_IMAGE=true" >> $GITHUB_ENV
@@ -49,13 +52,13 @@ jobs:
 
       - name: Build and Push Docker Image
         if: env.BUILD_DOCKER_IMAGE == 'true'
-        uses: docker/build-push-action@v4
+        uses: docker/build-push-action@v6.11.0
         with:
-          context: .
-          file: ldnmp/nginx/Dockerfile
+          context: "{{defaultContext}}:ldnmp/nginx"
+          file: Dockerfile
           push: true
           tags: |
-            "honeok/nginx:${{ env.LATEST_NGINX_VERSION }}-alpine${{ env.ALPINE_VERSION }}"
+            "honeok/nginx:${{ env.LATEST_NGINX_VERSION }}-alpine${{ env.LATEST_NGX_TAG }}"
             "honeok/nginx:alpine"
           platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
           build-args: |
